### ISSUE TITLE
Optimized_tests failing, Direct_tests very slow

### ISSUE THREAD

**Issue by timharley** [twitter/torch-autograd#32]
Is there a stable version of this package yet? Currently, if running against HEAD, 24/35 of the Optimized_* tests fail with an error. The Direct tests pass for me, but some are very slow (>30s per test):
* Direct_NNFunc_CNN
* Direct_Models_SpatialNetwork

**Comment by clementfarabet** [comment]
My bad, I broke it with cc2104076e02a72064ac50c549d938524e22991a . Looking for a patch now.

**Comment by clementfarabet** [comment]
Actually, nvm, it's not broken. It sounds like you have an install issue. Can you try to force remove autograd and re-install it? Also make sure you have the latest nn:

```
luarocks remove --force autograd
luarocks install nn
luarocks install autograd
```

**Comment by timharley** [comment]
Sorry, that doesn't fix it. I've tried a freshly building torch itself too.

**Comment by clementfarabet** [comment]
Not sure what's going on. Are you on OS X?

I just did:

```
cd /tmp
git clone https://github.com/torch/distro.git --recursive
cd distro
./install.sh
no
cd ..
./distro/install/bin/luarocks install autograd
git clone https://github.com/twitter/torch-autograd autograd
./distro/install/bin/th autograd/test/test.lua
```

and all tests pass.

Can you paste the output of your tests?

**Comment by soumith** [comment]
@clementfarabet you should setup a quick contbuild in travis using this script:
https://github.com/torch/nngraph/blob/master/.travis.yml

**Comment by clementfarabet** [comment]
@soumith thanks for the script.

**Comment by clementfarabet** [comment]
@timharley sorry, just seeing the error on Travis now, we're not seeing this on our boxes. Investigating.

**Comment by alexbw** [comment]
@timharley what linear algebra package are you building Torch against? OpenBLAS, MKL, or something else?

**Comment by alexbw** [comment]
@timharley also, can you try running the tests with `th`, as opposed to `lua` or `luajit`?

**Comment by clementfarabet** [comment]
Problems have been fixed in https://github.com/twitter/torch-autograd/pull/35 ! Travis tests now passing.

**Comment by alexbw** [comment]
@timharley the slowness on CNN and MLP networks might still persist. Open a separate issue if so.

**Comment by clementfarabet** [comment]
Oh yes sorry – I might have closed a bit aggressively :-).
